### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by seece** [seece/DemoRocker#1]
- [ ] basic track views
- [ ] multi track view
- [ ] audio waveform
- [ ] saving
- [x] basic XML loading
- [ ] tweak controls
- [ ] websockets
